[package]
name = "l3_orderbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
barter-data = "0.7.0"
barter-integration = "0.5.3"
chrono = "0.4.23"
tokio = "1.23.0"
